version: '3.0'
services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 443:443
      - 5000:5000
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/etod.me.crt
      REGISTRY_HTTP_TLS_KEY: /certs/etod.me.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      SEARCH_BACKEND: sqlalchemy
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs
      - ./auth:/auth
    networks:
      - registry-ui-net

  ui:
    restart: always
    image: joxit/docker-registry-ui:static
    ports:
      - 80:80
    environment:
      - REGISTRY_URL=https://registry:443
      - DELETE_IMAGES=true
      - REGISTRY_TITLE=Mobtaker Hub
    networks:
      - registry-ui-net

networks:
  registry-ui-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.14.17.0/24
